apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vllm.fullname" . }}-secret
  labels:
    {{- include "vllm.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-key: {{ .Values.api.key | quote }}
  {{- if .Values.api.hfToken }}
  hf-token: {{ .Values.api.hfToken | quote }}
  {{- end }}