{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "vllm.fullname" . }}-metrics
  labels:
    {{- include "vllm.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "vllm.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    path: {{ .Values.monitoring.path }}
    interval: 30s
    scrapeTimeout: