apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-comparator
  labels:
    app: pdf-comparator
spec:
  replicas: {{ .Values.app.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: pdf-comparator
  template:
    metadata:
      labels:
        app: pdf-comparator
    spec:
      containers:
      - name: pdf-comparator
        image: "{{ .Values.app.image.repository | default "python" }}:{{ .Values.app.image.tag | default "3.10-slim" }}"
        imagePullPolicy: Always
        command: ["sh", "-c", "echo 'Demo deployment' && python -m http.server 8000"]
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: VLLM_ENDPOINT
          value: {{ .Values.vllm.endpoint | quote }}
        - name: VLLM_MODEL_NAME
          value: {{ .Values.vllm.model.name | quote }}
        - name: LOG_LEVEL
          value: {{ .Values.config.logLevel | quote }}
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
