{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: pdf-comparator-route
  labels:
    app: pdf-comparator
spec:
  to:
    kind: Service
    name: pdf-comparator-service
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{- end }}
