apiVersion: v1
kind: Service
metadata:
  name: pdf-comparator-service
  labels:
    app: pdf-comparator
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: pdf-comparator
